apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  group: otus.homework
  scope: Namespaced
  names:
    plural: mysqls
    singular: mysql
    kind: MySQL
    shortNames:
    - sql
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  description: "Docker image, which will be used for MySQL container"
                  example: "mysql:8.1"
                database:
                  type: string
                  description: "Database name"
                  minLength: 1
                  maxLength: 65
                  example: "otus_db"
                password:
                  type: string
                  minLength: 1
                  maxLength: 20
                  description: "Database password"
                storage_size:
                  type: string
                  description: "Storage size in Gi"
                  example: "2Gi"
              required:
                - image
                - database
                - password
                - storage_size
  
      