apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-mysql-sa
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-full-access
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-sa-binding
subjects:
  - kind: ServiceAccount
    name: admin-mysql-sa
    namespace: homework
roleRef:
  kind: ClusterRole
  name: admin-full-access
  apiGroup: rbac.authorization.k8s.io
