apiVersion: v1
kind: Pod
metadata:
  name: page-downloader
spec:
  volumes:
    - name: html
      emptyDir: {}
      
  initContainers:
    - name: download-page
      image: busybox
      command: 
        [
          "wget",
          "-O",
          "/html/index.html",
          "https://receipts-app.com/de"
        ]
      volumeMounts:
        - name: html
          mountPath: /html
          
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html