apiVersion: v2
name: otus-helm-chart-1
version: 0.1.0
description: Helm Chart for Otus
type: application

dependencies:
  - name: redis
    version: 24.1.0
    repository: "oci://registry-1.docker.io/bitnamicharts"