apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: "{{ .Values.namespace }}"
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-admin
  namespace: "{{ .Values.namespace }}"
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: "{{ .Values.namespace }}"
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io