apiVersion: v1
kind: Service
metadata:
  name: page-downloader-svc
  namespace: homework 
spec:
  type: NodePort
  selector:
    app: homework-1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081