releases:
  - name: kafka-prod
    namespace: prod
    createNamespace: true
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    values:
      - values-prod.yaml
      
  - name: kafka-dev
    namespace: dev
    createNamespace: true
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    values:
      - values-dev.yaml
    